import { CmsResourceConfig } from '../../services/api';

export const CMS_CONFIGS: Record<string, CmsResourceConfig> = {
  cities: {
    resource: 'cities',
    title: '城市管理',
    nameField: 'name',
    showCity: false,
    cityRequired: false,
    fields: ['displayNo', 'summary', 'coverImage'],
  },
  banners: {
    resource: 'banners',
    title: '轮播图管理',
    nameField: 'title',
    showCity: true,
    cityRequired: false,
    fields: ['imageUrl', 'title'],
  },
  scenics: {
    resource: 'scenics',
    title: '景点管理',
    nameField: 'title',
    showCity: true,
    cityRequired: true,
    fields: ['summary', 'coverImage', 'galleryImages', 'tags', 'address', 'priceLabel', 'bookingChannel', 'openingHours', 'checkinPoints', 'notice', 'homeRecommended'],
  },
  hotels: {
    resource: 'hotels',
    title: '住宿管理',
    nameField: 'title',
    showCity: true,
    cityRequired: true,
    fields: ['summary', 'coverImage', 'galleryImages', 'tags', 'address', 'priceLabel', 'scenicDriveTime', 'roomTypes', 'facilities', 'notice'],
  },
  'car-rentals': {
    resource: 'car-rentals',
    title: '租车管理',
    nameField: 'title',
    showCity: true,
    cityRequired: true,
    fields: ['summary', 'coverImage', 'galleryImages', 'tags', 'address', 'priceLabel', 'notice'],
  },
  products: {
    resource: 'products',
    title: '文创商品',
    nameField: 'title',
    showCity: true,
    cityRequired: false,
    fields: ['summary', 'coverImage', 'galleryImages', 'price', 'externalLink', 'homeRecommended'],
  },
  guides: {
    resource: 'guides',
    title: '讲解员管理',
    nameField: 'name',
    showCity: true,
    cityRequired: false,
    fields: ['avatarUrl', 'yearsExperience', 'intro', 'quoteText'],
  },
  cases: {
    resource: 'cases',
    title: '案例截图',
    nameField: 'title',
    showCity: true,
    cityRequired: false,
    fields: ['caseType', 'coverImage', 'galleryImages', 'title'],
  },
  'trip-reminders': {
    resource: 'trip-reminders',
    title: '行程提醒',
    nameField: 'title',
    showCity: true,
    cityRequired: false,
    fields: ['weatherHint', 'content'],
  },
};
